### ISSUE TITLE
How to mask out of borders?

### ISSUE THREAD

**Issue by gencharitaci** [Jacobe2169/map-of-wordcloud#1]
Thanks for your amazing work. 

I want mask out of borders and show in transparent background, how can I do that ?

**Comment by jacquesfize** [comment]
Hi @gencharitaci,

To mask the borders, change the stroke-width to 0 in the function `contours_to_polygon_svg` in the `helpers.py` file  like this :

```python
def contours_to_polygon_svg(contours,color="white"):
    poly_str = ""
    for contour in contours:
        points_str= " ".join(["{0},{1}".format(c[1],c[0]) for c in contour]) # lat and lon so inverse order is required
        poly_str+="""\n<polygon points="{0}" style="fill-opacity:0;fill:lime;stroke:{1};stroke-width:0" />\n""".format(points_str,color)
    return poly_str
```

To have a transparent background change the Worldcloud `background-color `parameters in the `map.py` file  like this:

```python
wc = WordCloud(
        background_color="rgba(255, 255, 255, 0)", mode="RGBA",#background_color="rgb(125,125,125)",
        max_words=2000,
        mask=mask_geo,
        stopwords=[],
        contour_width=3,
        contour_color="black",
        #font_path="./Jost/Jost-VariableFont_ital,wght.ttf",
        color_func=single_color
    )
```

and finally since your background is transparent change the color in the `singlecolor` function here: https://github.com/Jacobe2169/map-of-wordcloud/blob/04d3502d4b851a588a21acdf6a0bf75cd8b5fe37/helpers.py#L39 

Bests,
Jacques

**Comment by gencharitaci** [comment]
Thank you so much. It worked for "svg" but it didn't work for "png" format. But "svg" is ok for me.
